version: 2.1
jobs:
  run-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
      - run:
          name: Install nextflow
          command: |
            echo Install nextflow
            curl -fsSL get.nextflow.io | bash
      - run:
          name: Install conda
          command: |
            mkdir -p ~/miniconda3
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
            bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
            rm -rf ~/miniconda3/miniconda.sh
            echo $PATH
            source ~/.bashrc
            source /home/circleci/miniconda3/etc/profile.d/conda.sh
            echo $PATH
            conda info --envs
      - setup_remote_docker:
          version: 20.10.14       
      - run:
          name: "Run test using conda"
          command: |
            source /home/circleci/miniconda3/etc/profile.d/conda.sh
            #docker pull rtlabcbm/fidelityfinder_img:latest
            ./nextflow run main.nf -profile conda,test
          no_output_timeout: 30m      
      - store_artifacts:
          path: /home/circleci/project/Results


workflows:
  test-workflow:
    jobs:
      - run-test
